from enum import Enum


class DeepModelType(Enum):
    """Deep Learning Model Types."""

    NSTRANSFORMER = "NSTransformer"
    MAMBA = "Mamba"
    LSTM = "LSTM"
    GRU = "GRU"
    XLSTM = "xLSTM"
    SNN = "SNN"
    MLP = "MLP"
    RBF = "RBF"
    AE = "AE"
    DAE = "DAE"
    SAE = "SAE"
    STACKED_AE = "StackedAE"
    HOPFIELD = "Hopfield"
    RBM = "RBM"
    ESN = "ESN"
    ELM = "ELM"
    SOM = "SOM"
    CAPSULE = "Capsule"
    CNN = "CNN"
    PERCEPTRON = "Perceptron"
    MARKOV_CHAIN = "MarkovChain"
    BM = "BM"
    DBN = "DBN"
    DCN = "DCN"
    DECONV = "Deconv"
    AUTO_DECONV = "AutoDeconv"
    DCIGN = "DCIGN"
    LSM = "LSM"
    RESNET = "ResNet"
    DNC = "DNC"
    NTM = "NTM"
    ATTENTION = "Attention"
    FLOW = "Flow"
    NODE = "NODE"
    LVQ = "LVQ"
    PINN = "PINN"
    VAE = "VAE"


class MacModelType(Enum):
    """Machine Learning (Classical) Model Types."""

    LINEAR_REGRESSION = "LinearRegression"
    RIDGE = "Ridge"
    LASSO = "Lasso"
    LARS = "LARS"
    ELASTIC_NET = "ElasticNet"
    LOGISTIC_REGRESSION = "LogisticRegression"
    POLYNOMIAL = "Polynomial"
    DECISION_TREE = "DecisionTree"
    CART = "CART"
    ID3 = "ID3"
    C45 = "C45"
    C50 = "C50"
    CHAID = "CHAID"
    DECISION_STUMP = "DecisionStump"
    CONDITIONAL_TREE = "ConditionalTree"
    M5 = "M5"
    RANDOM_FOREST = "RandomForest"
    GRADIENT_BOOSTING = "GradientBoosting"
    GBM = "GBM"
    GBRT = "GBRT"
    ADA_BOOST = "AdaBoost"
    BAGGING = "Bagging"
    STACKING = "Stacking"
    VOTING = "Voting"
    WEIGHTED_AVERAGE = "WeightedAverage"
    BLENDING = "Blending"
    XGBOOST = "XGBoost"
    LIGHTGBM = "LightGBM"
    KNN = "kNN"
    SVM = "SVM"
    SVR = "SVR"
    LINEAR_SVM = "LinearSVM"
    NU_SVM = "NuSVM"
    ONE_CLASS_SVM = "OneClassSVM"
    LSSVM = "LSSVM"
    TWSVM = "TWSVM"
    NAIVE_BAYES = "NaiveBayes"
    GAUSSIAN_NB = "GaussianNB"
    MULTINOMIAL_NB = "MultinomialNB"
    AODE = "AODE"
    BAYESIAN_NETWORK = "BayesianNetwork"
    BBN = "BBN"
    BN = "BN"
    OLSR = "OLSR"
    STEPWISE = "Stepwise"
    MARS = "MARS"
    LOESS = "LOESS"
    LWL = "LWL"


class HelperModelType(Enum):
    """Helper Model Types (Clustering, Dim Reduction, etc.)."""

    # Clustering
    KMEANS = "kmeans"
    HIERARCHICAL = "hierarchical"
    DBSCAN = "dbscan"
    GMM = "gmm"
    EM = "em"
    KMEDIANS = "kmedians"
    # Dimensionality Reduction
    PCA = "pca"
    TSNE = "tsne"
    LDA = "lda"
    PCR = "pcr"
    PLSR = "plsr"
    MDS = "mds"
    SAMMON = "sammon"
    PP = "pp"
    MDA = "mda"
    QDA = "qda"
    FDA = "fda"
    UMAP = "umap"
    # Association Rule Learning
    APRIORI = "apriori"
    FPGROWTH = "fpgrowth"
    ECLAT = "eclat"
